name: short-number

services:
    app:
        build:
            context: .
        image: short-number
        volumes:
            - .:/app
        environment:
            - TERM=xterm-256color
        tty: true
        stdin_open: true
